### ISSUE TITLE
Are You Planning To Continue?

### ISSUE THREAD

**Issue by turp** [behzad888/Aurelia-styleguide#1]
Started reading your style guide and realized there is still more work to do on it. Do you plan to continue with this effort? Or do you think that http://aurelia.io/docs.html has replaced the need for this document?

Thanks
Jay

**Comment by behzad888** [comment]
Hi Jay,
Yes i have. I apologize for delays in doing it. but i'll complete it soon

**Comment by turp** [comment]
No worries. Glad you will continue. What I've read so far is good and am looking forward to reading more
